# Unified paths configuration
user: eabe

# Base directories
project_dir: "/gscratch/portia/${paths.user}/Research/MyRepos/TheSphinx2026"
base_dir: "/gscratch/portia/${paths.user}/TheSphinx/${version}"
save_dir: ${multirun_save_dir:${paths.base_dir},${run_id}}
log_dir:  "${paths.save_dir}/logs/"
ckpt_dir: "${paths.save_dir}/ckpt/"
fig_dir:  "${paths.save_dir}/figures/"
data_dir: "/gscratch/portia/${paths.user}/TheSphinx/data"

# Submodule paths (relative to project_dir)
fly_mimic_dir: "${paths.project_dir}/sphinx_training"
body_models_dir: "${paths.project_dir}/sphinx_training/fruitfly_body_models"

# vnc_sims data paths
connectome_data_dir: "${paths.project_dir}/data/connectome/C_elegans"
