name: fly_tracking
channels:
  - conda-forge
  - menpo
  - anaconda
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - pip
  - black
  - glew
  - mesalib
  - mesa-libgl-cos6-x86_64
  - glfw3
  - ipykernel
  - ffmpeg
  - pip
  - pip:
      - "--editable=."
      - hydra-core
      - jax[cuda12]
      - h5py
      - natsort
      - tqdm
      - mediapy
      - imageio[ffmpeg]
variables:             # Set MuJoCo environment variables
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl