# Copyright 2024 The Brax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Proximal policy optimization training.

See: https://arxiv.org/pdf/1707.06347.pdf
"""

from typing import Any, Tuple

from brax.training import types
from . import ppo_networks
from brax.training.types import Params
import flax
import optax
import jax
import jax.numpy as jnp


@flax.struct.dataclass
class PPONetworkParams:
    """Contains training state for the learner."""

    policy: Params
    value: Params


def compute_gae(
    truncation: jnp.ndarray,
    termination: jnp.ndarray,
    rewards: jnp.ndarray,
    values: jnp.ndarray,
    bootstrap_value: jnp.ndarray,
    lambda_: float = 1.0,
    discount: float = 0.99,
):
    """Calculates the Generalized Advantage Estimation (GAE).

    Args:
      truncation: A float32 tensor of shape [T, B] with truncation signal.
      termination: A float32 tensor of shape [T, B] with termination signal.
      rewards: A float32 tensor of shape [T, B] containing rewards generated by
        following the behaviour policy.
      values: A float32 tensor of shape [T, B] with the value function estimates
        wrt. the target policy.
      bootstrap_value: A float32 of shape [B] with the value function estimate at
        time T.
      lambda_: Mix between 1-step (lambda_=0) and n-step (lambda_=1). Defaults to
        lambda_=1.
      discount: TD discount.

    Returns:
      A float32 tensor of shape [T, B]. Can be used as target to
        train a baseline (V(x_t) - vs_t)^2.
      A float32 tensor of shape [T, B] of advantages.
    """

    truncation_mask = 1 - truncation
    # Append bootstrapped value to get [v1, ..., v_t+1]
    values_t_plus_1 = jnp.concatenate(
        [values[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0
    )
    deltas = rewards + discount * (1 - termination) * values_t_plus_1 - values
    deltas *= truncation_mask

    acc = jnp.zeros_like(bootstrap_value)
    vs_minus_v_xs = []

    def compute_vs_minus_v_xs(carry, target_t):
        lambda_, acc = carry
        truncation_mask, delta, termination = target_t
        acc = delta + discount * (1 - termination) * truncation_mask * lambda_ * acc
        return (lambda_, acc), (acc)

    (_, _), (vs_minus_v_xs) = jax.lax.scan(
        compute_vs_minus_v_xs,
        (lambda_, acc),
        (truncation_mask, deltas, termination),
        length=int(truncation_mask.shape[0]),
        reverse=True,
    )
    # Add V(x_s) to get v_s.
    vs = jnp.add(vs_minus_v_xs, values)

    vs_t_plus_1 = jnp.concatenate([vs[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0)
    advantages = (
        rewards + discount * (1 - termination) * vs_t_plus_1 - values
    ) * truncation_mask
    return jax.lax.stop_gradient(vs), jax.lax.stop_gradient(advantages)


def compute_kl_to_gaussian_prior(
    latent_mean: jnp.ndarray,
    latent_logvar: jnp.ndarray,
) -> jnp.ndarray:
    """Compute KL divergence from latent distribution to standard Gaussian prior.

    Computes KL(q(z|x) || p(z)) where q(z|x) = N(latent_mean, exp(latent_logvar))
    and p(z) = N(0, I).

    Args:
        latent_mean: Mean of the latent distribution, shape [T, B, D].
        latent_logvar: Log variance of the latent distribution, shape [T, B, D].

    Returns:
        Scalar KL divergence loss (mean over all dimensions and batch).
    """
    return -0.5 * jnp.mean(
        1 + latent_logvar - jnp.square(latent_mean) - jnp.exp(latent_logvar)
    )


def compute_ar1_temporal_loss(
    latent_mean: jnp.ndarray,
    discount: jnp.ndarray,
    truncation: jnp.ndarray,
) -> jnp.ndarray:
    """Compute AR(1) temporal smoothness loss for latent intentions.

    Penalizes large changes between consecutive latent means. Pairs that cross
    episode boundaries (done or truncated) are masked out.

    Args:
        latent_mean: Mean of the latent distribution, shape [T, B, D].
        discount: Discount signal, shape [T, B]. 0 indicates episode end.
        truncation: Truncation signal, shape [T, B]. 1 indicates truncation.

    Returns:
        Scalar L2 loss between consecutive latent means (masked and normalized).
    """
    z_prev = latent_mean[:-1]
    z_curr = latent_mean[1:]
    valid_mask = discount[:-1] * (1 - truncation[:-1])
    l2_diff = jnp.mean(jnp.square(z_curr - z_prev), axis=-1)
    masked_l2 = l2_diff * valid_mask
    return jnp.sum(masked_l2) / jnp.maximum(jnp.sum(valid_mask), 1.0)


def compute_ppo_loss(
    params: PPONetworkParams,
    normalizer_params: Any,
    data: types.Transition,
    rng: jnp.ndarray,
    step: int,
    ppo_network: ppo_networks.PPONetworks,
    entropy_cost: float = 1e-4,
    kl_weight: float = 1e-3,
    mmd_weight: float = 1e-3,
    discounting: float = 0.9,
    reward_scaling: float = 1.0,
    gae_lambda: float = 0.95,
    clipping_epsilon: float = 0.3,
    normalize_advantage: bool = True,
    kl_loss: bool = False,
    mmd_loss: bool = False,
    ar1_weight: float = 0.0,
    use_kl_schedule: bool=True,
    use_mmd_schedule: bool=True,
    use_ar1_schedule: bool=False,
) -> Tuple[jnp.ndarray, types.Metrics]:
    """Computes PPO loss.

    Args:
      params: Network parameters,
      normalizer_params: Parameters of the normalizer.
      data: Transition that with leading dimension [B, T]. extra fields required
        are ['state_extras']['truncation'] ['policy_extras']['raw_action']
          ['policy_extras']['log_prob']
      rng: Random key
      ppo_network: PPO networks.
      entropy_cost: entropy cost.
      discounting: discounting,
      reward_scaling: reward multiplier.
      gae_lambda: General advantage estimation lambda.
      clipping_epsilon: Policy loss clipping epsilon
      normalize_advantage: whether to normalize advantage estimate

    Returns:
      A tuple (loss, metrics)
    """

    _, policy_key, entropy_key = jax.random.split(rng, 3)
    parametric_action_distribution = ppo_network.parametric_action_distribution
    policy_apply = ppo_network.policy_network.apply
    value_apply = ppo_network.value_network.apply

    # Put the time dimension first.
    data = jax.tree_util.tree_map(lambda x: jnp.swapaxes(x, 0, 1), data)

    # Check for stored policy_rng for deterministic stochastic layer replay
    policy_rng = data.extras["policy_extras"].get("policy_rng")

    if policy_rng is not None:
        # Deterministic replay: use stored per-sample RNGs so the same z is
        # sampled as during the forward rollout (fixes KL loss inconsistency).
        obs_leaf = jax.tree_util.tree_leaves(data.observation)[0]
        T, B = obs_leaf.shape[:2]
        flat_obs = jax.tree_util.tree_map(
            lambda x: x.reshape((T * B,) + x.shape[2:]), data.observation
        )
        flat_rng = policy_rng.reshape((T * B, 2))
        flat_logits, flat_extras = policy_apply(
            normalizer_params, params.policy, flat_obs, flat_rng
        )
        policy_logits = flat_logits.reshape((T, B) + flat_logits.shape[1:])
        extras = jax.tree_util.tree_map(
            lambda x: x.reshape((T, B) + x.shape[1:]), flat_extras
        )
    else:
        # Standard path: use fresh RNG
        policy_logits, extras = policy_apply(
            normalizer_params, params.policy, data.observation, policy_key
        )

    policy_logits = jnp.nan_to_num(policy_logits, nan=0.0, posinf=10.0, neginf=-10.0)

    baseline = value_apply(normalizer_params, params.value, data.observation)
    baseline = jnp.nan_to_num(baseline, nan=0.0)

    bootstrap_value = value_apply(
        normalizer_params, params.value, data.next_observation[-1]
    )
    bootstrap_value = jnp.nan_to_num(bootstrap_value, nan=0.0)

    rewards = data.reward * reward_scaling
    # Clip rewards to prevent extreme values
    rewards = jnp.clip(rewards, -1e5, 1e5)
    rewards = jnp.nan_to_num(rewards, nan=0.0)
    
    truncation = data.extras["state_extras"]["truncation"]
    termination = (1 - data.discount) * (1 - truncation)

    target_action_log_probs = parametric_action_distribution.log_prob(
        policy_logits, data.extras["policy_extras"]["raw_action"]
    )
    behaviour_action_log_probs = data.extras["policy_extras"]["log_prob"]

    vs, advantages = compute_gae(
        truncation=truncation,
        termination=termination,
        rewards=rewards,
        values=baseline,
        bootstrap_value=bootstrap_value,
        lambda_=gae_lambda,
        discount=discounting,
    )
    
    # Check for NaN in GAE computation
    vs = jnp.nan_to_num(vs, nan=0.0, posinf=1e6, neginf=-1e6)
    advantages = jnp.nan_to_num(advantages, nan=0.0, posinf=1e6, neginf=-1e6)
    
    if normalize_advantage:
        adv_mean = advantages.mean()
        adv_std = advantages.std()
        # Prevent division by zero
        adv_std = jnp.maximum(adv_std, 1e-8)
        advantages = (advantages - adv_mean) / adv_std
    
    # Clip log probability ratio to prevent extreme values
    log_ratio = jnp.clip(target_action_log_probs - behaviour_action_log_probs, -20.0, 20.0)
    rho_s = jnp.exp(log_ratio)

    surrogate_loss1 = rho_s * advantages
    surrogate_loss2 = (
        jnp.clip(rho_s, 1 - clipping_epsilon, 1 + clipping_epsilon) * advantages
    )

    policy_loss = -jnp.mean(jnp.minimum(surrogate_loss1, surrogate_loss2))
    
    # Clip policy loss to prevent extreme values
    policy_loss = jnp.clip(policy_loss, -1e6, 1e6)

    # Value function loss with clipping to prevent explosion
    v_error = jnp.clip(vs - baseline, -1e5, 1e5)
    v_loss = jnp.mean(v_error * v_error) * 0.5 * 0.5

    # Entropy reward with safety check
    entropy = jnp.mean(
        parametric_action_distribution.entropy(policy_logits, entropy_key)
    )
    # Clip entropy to reasonable range (negative entropy is log probability)
    entropy = jnp.clip(entropy, -1e5, 1e5)
    entropy_loss = entropy_cost * -entropy

    # KL Divergence and AR1 temporal smoothness for latent layer
    if kl_loss:
        latent_mean = extras["latent_mean"]
        latent_logvar = extras["latent_logvar"]

        # Clip to prevent exp() overflow
        latent_logvar = jnp.clip(latent_logvar, -100.0, 100.0)
        latent_mean_clipped = jnp.clip(latent_mean, -100.0, 100.0)

        current_kl_weight = kl_weight(step) if use_kl_schedule else kl_weight
        current_ar1_weight = ar1_weight(step) if use_ar1_schedule else ar1_weight

        # KL divergence to standard Gaussian prior N(0, I)
        kl_divergence = compute_kl_to_gaussian_prior(latent_mean_clipped, latent_logvar)
        kl_divergence = jnp.clip(kl_divergence, 0.0, 1e5)

        # AR1 temporal smoothness loss on latent means
        ar1_loss_val = compute_ar1_temporal_loss(latent_mean, data.discount, truncation)
        ar1_loss_val = jnp.clip(ar1_loss_val, 0.0, 1e5)

        kl_latent_loss = current_kl_weight * kl_divergence + current_ar1_weight * ar1_loss_val
    else:
        kl_latent_loss = 0
        current_kl_weight = 0
        current_ar1_weight = 0
        kl_divergence = 0
        ar1_loss_val = 0
    # MMD loss
    if mmd_loss:
        z = extras['z']
        z_sample = jax.random.normal(rng, shape=z.shape)
        if use_mmd_schedule:
            mmd_weight_val = mmd_weight(step)
        else:
            mmd_weight_val = mmd_weight
        # Compute MMD loss
        mmd = batched_mmd(z_sample, z)
        # Clip MMD to prevent extreme values
        mmd = jnp.clip(mmd, 0.0, 1e5)
        mmd_loss_val = mmd_weight_val * jnp.mean(mmd)
    else:
        mmd_loss_val = 0

    total_loss = policy_loss + v_loss + entropy_loss + kl_latent_loss + mmd_loss_val
    
    # Final safety check - replace NaN with large finite value to signal error
    total_loss = jnp.nan_to_num(total_loss, nan=1e6, posinf=1e6, neginf=1e6)
    policy_loss = jnp.nan_to_num(policy_loss, nan=1e6)
    v_loss = jnp.nan_to_num(v_loss, nan=1e6)
    entropy_loss = jnp.nan_to_num(entropy_loss, nan=1e6)
    
    return total_loss, {
        "total_loss": total_loss,
        "policy_loss": policy_loss,
        "v_loss": v_loss,
        "kl_latent_loss": kl_latent_loss,
        "kl_divergence": kl_divergence,
        "ar1_loss": ar1_loss_val,
        "mmd_loss": mmd_loss_val,
        "entropy_loss": entropy_loss,
        "kl_weight": current_kl_weight,
        "ar1_weight": current_ar1_weight,
    }


def rbf_kernel(x, y, sigma_sqr=1.0):
    """
    Compute the RBF (Gaussian) kernel matrix between x and y.

    Args:
        x: [n_x, d] array
        y: [n_y, d] array
        sigma_sqr: float, bandwidth of the RBF kernel

    Returns:
        [n_x, n_y] kernel matrix
    """
    x_norm = jnp.sum(x**2, axis=1, keepdims=True)  # [n_x, 1]
    y_norm = jnp.sum(y**2, axis=1, keepdims=True)  # [n_y, 1]

    # Broadcasting to get pairwise squared Euclidean distances
    dists = x_norm - 2 * jnp.dot(x, y.T) + y_norm.T  # [n_x, n_y]
    return jnp.exp(-dists / (2 * sigma_sqr))


def compute_mmd(x, y, sigma_sqr=1.0):
    """
    Compute the Maximum Mean Discrepancy (MMD) between x and y using RBF kernel.

    Args:
        x: [n_x, d] array
        y: [n_y, d] array
        sigma_sqr: float, RBF kernel bandwidth

    Returns:
        Scalar MMD value
    """
    k_xx = rbf_kernel(x, x, sigma_sqr)
    k_yy = rbf_kernel(y, y, sigma_sqr)
    k_xy = rbf_kernel(x, y, sigma_sqr)

    mmd = jnp.mean(k_xx) + jnp.mean(k_yy) - 2 * jnp.mean(k_xy)
    return mmd

def batched_mmd(x_batch, y_batch, sigma_sqr=1.0):
    """
    Batched MMD computation across a batch of distributions.

    Args:
        x_batch: [batch_size, n_x, d] array
        y_batch: [batch_size, n_y, d] array
        sigma_sqr: float, RBF kernel bandwidth

    Returns:
        [batch_size] array of MMD values
    """
    return jax.vmap(compute_mmd, in_axes=(0, 0, None))(x_batch, y_batch, sigma_sqr)

def create_ramp_schedule(
    max_value: float = 0.1,
    min_value: float = 0.001,
    ramp_steps: int = 1000,
    warmup_steps: int = 0,
    smoothing: str = 'linear'
) -> optax.Schedule:
    """
    Creates a schedule that smoothly ramps from 0 to a maximum value.
    """
    def schedule_fn(step):
        step = jnp.asarray(step, dtype=jnp.float32)
        progress = jnp.clip(
            (step - warmup_steps) / ramp_steps,
            min_value,
            1
        )
        
        if smoothing == 'cosine':
            progress = 0.5 * (1 - jnp.cos(jnp.pi * progress))
        
        is_warmup = step < warmup_steps
        return jnp.where(is_warmup, min_value, progress * max_value)
    
    return schedule_fn

def cosine_annealing_schedule(
    init_value: float = 0.001,
    final_value: float = 0.1,
    max_steps: int =100,
    warmup_steps: int = 0,
    restart_steps: int = None
) -> optax.Schedule:
    """
    Creates a cosine annealing learning rate schedule with optional warmup and restart.
    
    Args:
        init_value: Initial learning rate value.
        final_value: Final learning rate value.
        max_steps: Total number of training steps.
        warmup_steps: Number of linear warmup steps (default: 0).
        restart_steps: Number of steps after which to restart the schedule (default: None).
            If None, no restarts will be applied.
    
    Returns:
        An optax.Schedule that computes the learning rate at each step.
    """
    def schedule(step_count):
        # Apply linear warmup if warmup_steps > 0
        if warmup_steps > 0:
            warmup_factor = jnp.minimum(1.0, step_count / warmup_steps)
            warmup_lr = init_value * warmup_factor
        else:
            warmup_lr = init_value
        # Apply cosine annealing with optional restart
        if restart_steps is not None:
            # Calculate cycle count and steps within current cycle
            cycle = step_count // restart_steps
            cycle_step = step_count % restart_steps
            
            # Apply cosine annealing within each cycle
            cosine_factor = 0.5 * (1 + jnp.cos(jnp.pi * cycle_step / restart_steps))
            cosine_lr = final_value + (init_value - final_value) * cosine_factor
            max_cycle = (max_steps // restart_steps) * restart_steps
            cosine_lr = jnp.where(step_count>=max_cycle,final_value,cosine_lr)
        else:
            # Ensure warmup is accounted for in the step count
            effective_step = jnp.maximum(0, step_count - warmup_steps)
            effective_max_steps = max_steps - warmup_steps
            
            # Standard cosine annealing schedule
            cosine_factor = 0.5 * (1 + jnp.cos(jnp.pi * effective_step / effective_max_steps))
            cosine_lr = final_value + (init_value - final_value) * cosine_factor
            cosine_lr = jnp.where(step_count>=max_steps,final_value,cosine_lr)
        # Use warmup LR during warmup, then transition to cosine schedule
        return jnp.where(step_count < warmup_steps, warmup_lr, cosine_lr)
    
    return schedule
